apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fitoglobe

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: fitbackend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: backend-config

            - secretRef:
                name: backend-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20